version: 0.2

env:
  parameter-store:
#    GITHUB_TOKEN: "/codebuild/github_token"
    GITHUB_TOKEN: /github_tokens

phases:
  install:
    commands:
      - ${CODEBUILD_SRC_DIR}/scripts/install.sh
  build:
    commands:
      - ${CODEBUILD_SRC_DIR}/scripts/build.sh
